name: CI
on: [push]
jobs:
  build:
    name: Benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7
      - name: Install Deps
        run: yarn
      - name: Benchmark
        run: pnpm -F app benchmark
