name: CI
on: push
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install Dependencies
        run: yarn
      - name: Run the tests
        run: yarn workspace app test:coverage
      - name: Benchmark
        run: yarn workspace app benchmark
