name: Version
on: push
jobs:
  version:
    name: Check if version has been updated
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Print Package Version
        run: |
          PACKAGE_VERSION=$(cat app/package.json \
            | grep version \
            | head -1 \
            | awk -F: '{ print $2 }' \
            | sed 's/[",]//g');

          echo $PACKAGE_VERSION;
