name: Version
on: push
jobs:
  version:
    name: Check if version has been updated
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v2
        with:
          path: main
      # - name: Checkout main branch
      #   uses: actions/checkout@v2
      #   with:
      #     ref: main
      #     path: main
      - uses: actions/checkout@v2
      - name: Print Package Versions
        run: |
          ls -la
        # run: |
        #   CURRENT_PACKAGE_VERSION=$(cat ./current/app/package.json \
        #     | grep version \
        #     | head -1 \
        #     | awk -F: '{ print $2 }' \
        #     | sed 's/[",]//g');
        #   echo $CURRENT_PACKAGE_VERSION;
